[package]

name = "voronoi-gen"
version = "0.1.0"
authors = [
    "Will Turner <rwturner17@gmail.com>"
]

[dependencies]
rand = "0.3"
ordered-float = "0.5.0"
log = "0.3"
env_logger = "0.4.3"
stopwatch = "0.0.7"